name: Precompile Binaries

on:
  push:
    branches:
      - main

env:
  MACOSX_DEPLOYMENT_TARGET: '13.3'
  IPHONEOS_DEPLOYMENT_TARGET: '15.0'

jobs:
  Precompile:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install GTK
        if: (matrix.os == 'ubuntu-22.04') || (matrix.os == 'ubuntu-22.04-arm')
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - name: Set SDKROOT for iOS
        if: (matrix.os == 'macOS-latest')
        run: echo "SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV
      - name: Precompile
        if: (matrix.os == 'ubuntu-22.04-arm') || (matrix.os == 'macOS-latest') || (matrix.os == 'windows-latest')
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=NathanKolbas/ort_dart
        working-directory: cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Install NDK
        uses: nttld/setup-ndk@v1
        if: (matrix.os == 'ubuntu-22.04')
        with:
          add-to-path: false
          ndk-version: r28
      - name: Precompile (with Android)
        if: (matrix.os == 'ubuntu-22.04')
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=NathanKolbas/ort_dart --android-sdk-location=/usr/local/lib/android/sdk --android-ndk-version=28.0.13004108 --android-min-sdk-version=28
        working-directory: cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
